# Kaggle dataset root
# Root directory of dataset (ABSOLUTE PATH FOR KAGGLE)
path: /kaggle/working/crackathon/data

# Image directories (relative to path)
train: images/train
val: images/val

# Number of classes
nc: 5

# Class names (ORDER MUST MATCH LABEL IDS)
names:
  0: longitudinal_crack
  1: transverse_crack
  2: alligator_crack
  3: other_corruption
  4: pothole
