# Kaggle dataset root (THIS MUST MATCH INPUT PANEL NAME)
path: /kaggle/input/crackathon

# Image directories relative to path
train: train/images
val: val/images

# Number of classes
nc: 5

# Class names (order MUST match label ids)
names:
  0: longitudinal_crack
  1: transverse_crack
  2: alligator_crack
  3: other_corruption
  4: pothole
