# Root of dataset
path: /content/drive/MyDrive/crackathon/data

# Train / Val images
train: images/train
val: images/val

# Classes (order must match labels)
names:
  0: longitudinal_crack
  1: transverse_crack
  2: alligator_crack
  3: other_corruption
  4: pothole
